// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/3/2026, 11:03:05 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/kimchaelin/Documents/study/cl-PortFolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/plugins/**/*.{js,ts,mjs}","/Users/kimchaelin/Documents/study/cl-PortFolio/composables/**/*.{js,ts,mjs}","/Users/kimchaelin/Documents/study/cl-PortFolio/utils/**/*.{js,ts,mjs}","/Users/kimchaelin/Documents/study/cl-PortFolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/cl-PortFolio/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;